name: Assume STS Role GH Actions Test
run-name: Assume STS Role GH Actions Test -- ${{ github.sha }}
on: workflow_dispatch

jobs:
  run:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable.yaml
    with:
      print_hello: true
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
