name: Assume STS Role GH Actions Test
run-name: Assume STS Role GH Actions Test -- ${{ github.sha }}
on: workflow_dispatch

jobs:
  run:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run STS role
        uses: ./.github/workflows/resuable.yaml
        with:
          print_hello: true
        secrets:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
