name: Assume STS Role GH Actions Test
run-name: Assume STS Role GH Actions Test -- ${{ github.sha }}
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsWorkflowRole
          aws-region: us-east-1
      - name: Run Docker container
        working-directory: assume-sts-role-gh-actions
        run: |
          docker-compose up --build
