on:
  workflow_call:
    inputs:
      print_hello:
        required: true
        type: boolean
    secrets:
      aws_account_id:
          required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assume STS Role
        uses: ./.github/actions/assume-sts-role
        with: 
          aws_account_id: ${{ secrets.aws_account_id }}
      - name: Print hello
        if: ${{ inputs.print_hello }}
        run: echo 'hello'
      - name: Run Docker container
        working-directory: assume-sts-role-gh-actions
        run: |
          docker compose up --build -d
      - name: Install dependencies
        working-directory: assume-sts-role-gh-actions
        run: |
          pip3 install -r requirements.txt
      - name: Run unit tests
        run: |
          python3 -m unittest
